name: hupr_texibooking
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  get: ^4.6.6
  fl_country_code_picker: ^0.1.9+1
  pin_code_fields: ^8.0.1
  flutter_switch: ^0.3.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  modal_progress_hud_nsn: ^0.5.1
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.7
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  firebase_core: ^2.26.0
  url_launcher: ^6.2.5
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.19
  slide_action: ^0.0.2
  intl: ^0.18.1
  syncfusion_flutter_gauges: ^25.1.35
  flutter_stripe: 
  get_storage: ^2.1.1
  new_version_plus: ^0.0.11
  file_picker: ^8.0.0+1
  custom_info_window: ^1.0.1
  webview_flutter: ^2.0.13
  flutter_inappwebview: ^6.0.0


 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

 